---
title: "Epigenetics on AnVIL: Nature vs Nurture"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: "Introduction to Epigenetics"
favicon: assets/AnVIL_style/anvil_favicon.ico
---


# Overview {-}

This activity is intended to serve as an introduction to the field of epigenetics, or the idea of "nature versus nurture". The first activity, [Explore the Epigenome](explore-the-epigenome#launch-the-genome-browser-gateway) leverages the UCSC Genome Browser - a powerful tool for visualizing genomic differences. This book is part of a series of books for the Genomic Data Science Analysis, Visualization, and Informatics Lab-space (AnVIL) of the National Human Genome Research Institute (NHGRI). 

## Skills Level {-}

<div class = "notice">
_Genetics_  
**Beginner**: minimal prior knowledge/skill helpful
 
_Programming skills_  
**Novice**: no programming experience needed
</div>

## Learning Objectives {-}

Learning objectives for this activity come from the [Genetics Core Competencies](https://genetics-gsa.org/education/genetics-learning-framework/):

- Discuss how DNA is packaged in the chromosomes in terms of histones, nucleosomes, and chromatin.  
- Defend how most cells can have the same genetic content and yet have different functions in the body.  
- Contrast the packaging of DNA into euchromatin versus heterochromatin in the context of histone modification, and DNA modification (where applicable).  
- Discuss the potential roles of DNA modification, histone modification, and non-coding RNA in epigenetic inheritance, both somatic and germline.  
- Discuss environmental impacts on epigenetic systems.  
- Describe how differential histone modification modulates gene activity and is utilized in developmental progression.  

### AnVIL Collection {-}

Additional guides are provided to help you with Workspaces, launch interactive tools, and start working with data. Learn more about AnVIL by visiting https://anvilproject.org or reading the [article in Cell Genomics](https://www.sciencedirect.com/science/article/pii/S2666979X21001063).

Please check out our full collection of AnVIL and related resources: https://hutchdatascience.org/AnVIL_Collection/

